#Database Configuration
#Sun Apr 26 23:23:55 EAT 2026
db.pool.size=10
db.driver=com.mysql.cj.jdbc.Driver
db.password=
db.username=root
db.url=jdbc\:mysql\://localhost\:3306/inventory_db?useSSL\=false&serverTimezone\=UTC&allowPublicKeyRetrieval\=true
